# Generated by Django 3.2.14 on 2022-11-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Contribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Logradouro')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=130, verbose_name='Nº da OS')),
                ('dt_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de solicitação')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referência')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do contribuinte')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do contribuinte')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone do contribuinte')),
                ('motivo_reclamacao', models.TextField(verbose_name='Motivo da reclamação')),
                ('dt_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Tipo de OS')),
            ],
        ),
        migrations.CreateModel(
            name='OS_ext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_veiculo', models.CharField(blank=True, max_length=14, verbose_name='Código do veículo')),
                ('equipe', models.ManyToManyField(blank=True, null=True, to='iluminacao.Equipe')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iluminacao.tipo_os'),
        ),
        migrations.CreateModel(
            name='MateriaisUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referência')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.bairro', verbose_name='Bairro')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.logradouro', verbose_name='Logradouro')),
            ],
        ),
    ]
