# Generated by Django 3.2.14 on 2022-11-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxerifado', '0001_initial'),
        ('iluminacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='contribuinte',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='motivo',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='bairro',
            field=models.CharField(default='Centro', max_length=150, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='cpf',
            field=models.CharField(default='15253517707', max_length=14, verbose_name='CPF do contribuinte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='logradouro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='iluminacao.logradouro', verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do contribuinte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone do contribuinte'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dt_conclusao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='motivo_reclamacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Motivo da reclamação'),
        ),
        migrations.CreateModel(
            name='OS_ext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_veiculo', models.CharField(blank=True, max_length=14, verbose_name='Código do veículo')),
                ('equipe', models.ManyToManyField(blank=True, null=True, to='iluminacao.Equipe')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaisUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxerifado.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
    ]
