# Generated by Django 3.2.14 on 2022-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_os',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de OS'),
        ),
    ]
