# Generated by Django 3.2.14 on 2022-11-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0002_auto_20221117_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=14, verbose_name='Tipo de OS')),
            ],
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dt_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dt_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de solicitação'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='motivo_reclamacao',
            field=models.TextField(verbose_name='Motivo da reclamação'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='numero',
            field=models.CharField(max_length=130, verbose_name='Nº da OS'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iluminacao.tipo_os'),
        ),
    ]
