# Generated by Django 3.2.14 on 2022-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0003_auto_20221117_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_os',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de OS'),
        ),
    ]
