# Generated by Django 3.2.16 on 2022-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0003_auto_20221117_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('0', 'Novo'), ('1', 'Aguardando'), ('2', 'Execução')], max_length=1, null=True, verbose_name='Status'),
        ),
    ]
