# Generated by Django 3.2.14 on 2022-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0004_alter_tipo_os_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='logradouro',
            field=models.CharField(max_length=150, verbose_name='Logradouro'),
        ),
    ]
