# Generated by Django 3.2.13 on 2022-12-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0004_alter_ordemdeservico_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
    ]
