# Generated by Django 3.2.16 on 2023-01-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0006_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_os',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla'),
        ),
    ]
