# Generated by Django 3.2.14 on 2022-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxerifado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estoque',
            new_name='Log_estoque',
        ),
        migrations.AlterModelOptions(
            name='log_estoque',
            options={'ordering': ['material__nome'], 'verbose_name': 'Log do estoque do material', 'verbose_name_plural': 'Log do estoque dos materiais'},
        ),
        migrations.AddField(
            model_name='material',
            name='qnt_em_estoque',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
