# Generated by Django 3.2.14 on 2022-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxerifado', '0002_auto_20221117_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['tipo__nome', 'nome', 'qnt_em_estoque'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.RemoveField(
            model_name='log_estoque',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='log_estoque',
            name='add_quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade p/ adicionar ao estoque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log_estoque',
            name='qnt_em_estoque',
            field=models.IntegerField(null=True),
        ),
    ]
